# Generated by Django 2.2.16 on 2021-12-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20211220_2037'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_cant_follow_himself',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follower_1',
        ),
    ]
