# Generated by Django 2.2.16 on 2021-12-21 17:47

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20211220_2047'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(user=django.db.models.expressions.F('user')), name='user_cant_follow_himself'),
        ),
    ]
