# Generated by Django 2.2.16 on 2021-12-21 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20211221_1843'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_cant_follow_himself',
        ),
    ]
